### ISSUE TITLE
a few questions about MESuSiE

### ISSUE THREAD

**Issue by arkyl** [borangao/MESuSiE#1]
Hi,
Thanks for the new software and congratulations on the new publication! 
We plan to utilize MESuSie on multi-ancestry QTL analysis, and have a few questions.

1. LD mismatch check 
We have individual level data for each ancestry and will generate QTL association and LD using the exact same genotype data. So there should be no issue of LD "mismatch" as the LD info are not derived from an outside ref panel. I am wondering if the LD mismatch check is necessary in this case. 

2. "Non-significant SNPs correlation with GWAS signals" in LD mismatch check
This is still relevant to LD mismatch but more of a general question. In the tutorial, for LD mismatch indicators, I think we will have info for the z, z_std_diff and logLR from kriging_rss(). What about some recommendations for the indicator of "non-significant SNPs correlation (abs(r)>0.8) with GWAS signals". Is pval>0.05 as non-significant and pval<1e-06 as significant signal good? or pval>0.05 as non-significant and pval<5e-08 as significant signal? I guess there is no direct output for this indicator so we will need to derive this.  

3. more than 2 ancestries
The examples on MESuSie seemed all to be on 2 ancestries. But I guess the software can be run on 3 ancestries as well. We have 3 ancestries (White/Black/Hispanic), and I am wondering if I can simply run MESuSie on 3 ancestries and I guess it will generate shared variants among 3 ancestries, shared variants between any subset of 2 ancestries, and one-ancestry specific variants. This is preferred as it would give more complete info per snp, but I don't know if a third ancestry may interfere with shared variant between 2 ancestries. So any advice on this is appreciated.  

Again congratulations on your new publication and thanks a lot for your advice!

Best,
Yue

**Comment by borangao** [comment]
Hi Yue,

Thanks for your interest in MESuSiE.

1. If individual level data is available, I would say LD mismatch check is not necessary.
2. I would suggest more stringent criteria. I recommend to use pval>0.05 as non-significant and pval<1e-06 as significant signal.
3. Yes, MESuSiE can be used on more than two ancestries. I suggest to use MESuSiE cautiously with more than 3 ancestries. As you may notice already, the causal configuration increases as number of ancestry increase. 

Hope it helps! Please let me know if you have further questions.

Best,
Boran

**Comment by arkyl** [comment]
Many thanks for your suggestions and such fast reply! Please close the thread.
Yue
