### ISSUE TITLE
Covariates in fine-mapping

### ISSUE THREAD

**Issue by Jesson-mark** [borangao/MESuSiE#10]
Hi Boran, 

thanks for your tool on trans-ancestry fine-mapping! 

Currently I'm trying to do trans-ancestry fine-mapping for two ancestries and both GWASs are performed with some covariates. 
I noticed that when running fine-mapping using SuSiE the genotype and phenotype are needed to [adjusted for covariates](https://stephenslab.github.io/susieR/articles/finemapping.html#a-note-on-covariate-adjustment). 

What I want to confirm is that whether the same step (i.e. adjust for covariates) are required to perform trans-ancestry fine-mapping using MESuSiE. 

Thanks!

Jie Wang

**Comment by borangao** [comment]
Dear Jie,

Thank you for your interest in MESuSiE. I would highly suggest following the same adjustment as suggested by SuSiE. Please let me know if you need further help from me.

Best,
Boran
