### ISSUE TITLE
would MAF difference in different ancestries affect the MESuSiE config?

### ISSUE THREAD

**Issue by arkyl** [borangao/MESuSiE#3]
Hi,
We have finished the preliminary run of MESuSiE, and as expected, most of the high config_pip snps belonged to shared ancestry config. For the ancestry specific config, we would hope to understand more. In particular, I am wondering if the MAF difference in ancestries would have a large effect on MESuSiE config.

E.g: 
A biological casual snp X is present in both race A and B with same effect, i.e. the true config is shared "A_B". However, X has a large MAF difference in A and B; let's say MAF is 0.06 in A and is 0.48 in B. Then even with the same sample size, the association would give equal effect size but much larger Z-score in B than in A. In this case, would MESuSiE possibly categorize the X as specific "B" instead of shared "A_B"? Let's suppose we only consider common alleles (MAF>0.05), should we check the MAF difference when determining ancestry specific snps? 

Your advice is greatly appreciated. Thanks!

Best,
Yue

**Comment by borangao** [comment]
Hi Yue,

It is a good question. I would say MESuSiE should correctly classify X as a shared causal SNP as long as the evidence of marginal association in ancestry B is strong enough. Hope it clarifies.

Best,
Boran

**Comment by arkyl** [comment]
Great! This is very helpful. Just to confirm: do you mean "as long as association in A is strong enough"? since A is the one with lower MAF and thus lower signal. 
Yue

**Comment by borangao** [comment]
Hi Yue,

Yeah, you are right! I mean the one with lower MAF has an association strong enough to be detected. Sorry for the typo there.

Best,
Boran

**Comment by arkyl** [comment]
Thanks a lot for continued help and explanation! Please close the thread.
Yue
