### ISSUE TITLE
Error while running MESuSiE with 4 ancestries

### ISSUE THREAD

**Issue by mpkol59** [borangao/MESuSiE#4]
Hello,
Great work with the software!

We tried running fine-mapping with MESuSiE using 4 different ancestries, and created the summ_stat and LD lists as shown below:

summ_stat_listB<- list("A"=A_example, "B"=B_example, "C"=C_example, "D"=D_example)
LD_listB<- list("A"=A_cov, "B"=B_cov, "C"=C_cov, "D"=D_cov)

We however encountered the following error when we ran the MESuSiE function as follows:

MESuSiE_res <- meSuSie_core(LD_listB, summ_stat_listB, L = 10, residual_variance = NULL, prior_weights = NULL,  ancestry_weight = NULL)
*************************************************************
# Start data processing for sufficient statistics 
Error in diag(sqrt(XtX.diag[[x]])) %*% R[[x]] : non-conformable arguments

What would you suggest as the best way to work around this? Do we need to indicate or change the default number of ancestries somewhere in the function?

Thank you.

**Comment by borangao** [comment]
Thank you for your interest in MESuSiE. It's a bit challenging to pinpoint the exact error without more details. It would be helpful if you could provide an example dataset.

In the meantime, my best guess is that there might be a different number of SNPs within each ancestry. You could try subsetting to a common set of SNPs within each ancestry and then rerun MESuSiE to see if that resolves the issue.
Hope it helps. Please let me know if you have further questions!
