### ISSUE TITLE
MESuSiE for interaction effects

### ISSUE THREAD

**Issue by froehlichbenedikt** [borangao/MESuSiE#5]
Congratulations on your very comprehensible publication and thank you so much for providing the code!

We thought of possible applications of MESuSiE to model discrete interaction effects, by using subpopulations depending on the value of the interaction variable, rather than different ancestries. Do you think this might be a possible use-case, and if so, do you already happen to work on possible applications?

If not, is there a reason this might not be an application of MESuSiE? Moreover, do you think it would be possible to expand MESuSiE to applications for multi-trait fine mapping with possible overlap of populations, e.g. by removing the requirement that the genotype matrix must be of block form?

Thank you so much in advance!
Best, Benedikt

**Comment by borangao** [comment]
Dear Benedikt,

Apologies for the delayed response, and thank you for your interest in MESuSiE. I’ve been transitioning into a new role.

I completely agree that MESuSiE can model interaction effects, such as stratifying individuals by sex or SES to observe differences across strata. I have conducted some initial work on sex-stratified analyses, and if you are interested in pursuing this type of analysis, feel free to reach out to me at gao824@purdue.edu. I recently joined Purdue University as an assistant professor and am open to collaborative exploration in this area!

As for multi-trait and ancestry fine-mapping, I am actively working on it, and I will let you know as soon as the manuscript is available on bioRxiv.

Thank you again for your thoughtful ideas, and I truly appreciate your input.

Best regards,
Boran
