### ISSUE TITLE
Effect Size Estimate?

### ISSUE THREAD

**Issue by harryyiheyang** [borangao/MESuSiE#7]
Hi @borangao 
While MESuSiE is already fast, stable, and effective, it may benefit some of my undergoing work if it could further provide the effect size estimates of non-zero causal variants for two traits. Alternatively, it would be equally useful if it could provide "alpha", "mu", "mu2".
Thank you very much.
Yihe Yang

**Comment by harryyiheyang** [comment]
Hi Boran,
I still have a problem in getting the effect size estimate. Could you please tell me how to complete coef(fit_mesusie)? For example, for mvsusieR, this will return a matrix consisting of the beta effect sizes for each trait. 
Best
Yihe

**Comment by borangao** [comment]
Dear Yihe,

Sorry for the late reply. I haven’t been regularly checking my UMich email
as I’m moving to Purdue. You can reach me at ***@***.**** going
forward.

Thank you for your interest in MESuSiE. As you may know, the output of
MESuSiE is a list containing multiple elements. For example, you can use
res$EB1 to extract the list of effect size matrices from the output object
res. The length of the list res$EB1 is *L*, and each element is a matrix of
size *(number of SNPs) × (number of ancestries)*, with entries representing
effect sizes.

Let me know if this helps or if you’d like further clarification.

Best,
Boran
Boran Gao
Ph.D. Candidate in Biostatistics
MPH Epidemiology
MS Biostatistics
University of Michigan School of Public health
7345462396
