### ISSUE TITLE
further filtering MESuSiE shared-ancestry signals by summary QTL pval and beta

### ISSUE THREAD

**Issue by arkyl** [borangao/MESuSiE#8]
Hi,
Thanks a lot for your previous help with MESuSiE analysis in three populations. We are mainly focusing on the signals shared across all populations, e.g: config.pip>0.5 in shared-in-all configuration. 

We noticed that some of these signals in summary QTL data had different effect sign across populations, and also some signals were non-significant (P>0.05) in some populations, with a few even non-significant in all populations. This is a bit unexpected, as I would have expected shared signals would have consistent effect sign, and reasonable significance across populations. So we are planning to have some further filtering, such as, same beta sign in all populations, or significant in at least one population, or significant in all populations,  etc.

We had in the past seen similar "conflicting cases" in single population SuSiE, that the identified causal signal (pip>0.9) is surely non-significant in summary QTL of good sample size. For MESuSie, I believe it is already quite conservative. But due to the complexity in cross-population fine-mapping, we would like to be even more conservative.  So I am wondering what you think about the further filtering we are planning, or maybe you have some criteria in mind. Any advice is greatly appreciated!

Best,
Yue

**Comment by borangao** [comment]
I just want to confirm my understanding. Have you flipped the sign of beta/Z based on the effect allele? Is this result after matching the effect alleles?

I would suggest first matching the effect alleles before conducting the analysis. I agree that it raises concerns when we observe a potential shared causal signal with opposite effects in different ancestries. For shared signal detection, my intuition is that it should be significant in at least one population. Another approach could be requiring significance across all populations and then running MESuSiE while tuning the shared causal signal proportion to 1.

Best,
Boran

**Comment by arkyl** [comment]
Hi,
Thanks a lot for the quick reply. Yes, all analyses were performed matching the effect allele. 

The observed conflicting beta signs mostly came together with non-significant signals. That is, when a signal was not significant in a population, its beta effect is virtually close to zero, so its sign can goes either way and certainly can be in opposite sign to other populations. 

But we did observe a case where a gene has conflicting beta sign at a snp quite significant in both non-Hispanic White (NHW) and AA populations. The snp is a single snp CS and its configuration is shared across all 3 populations (pip.config=0.999). Its effect allele freq in 3 populations  are NHW/AA/Hisp: 0.307/0.489/0.298; we noted the freq in AA is close to 0.5. We also tested to remove this snp and rerun MESuSiE; it gave the similar results on another snp in high LD with this one. The gene has more than 2000 snps. I had attempted to upload the summary and LD data for this gene but the size (>50Mb) seems too big for github. In any case, this example is not a common case. 

We tested using shared causal signal proportion to 1, by setting ancestry_weight=c(0,0,0,0,0,0,1). It gave similar results on the same snp. I guess since we are checking on snps already identified as shared across all populations, increasing ancestry_weight in shared_in_all probably wouldn't change much on this snp.

Thanks a lot for your confirming about checking the beta/pval in shared signals. Even in single population SuSieR we noticed a few non-significant signals; so in the multi-ancestry analysis, it can be quite complexed. Thus we may apply some empirical criteria to further filtering these signals.    

Your advice and suggestions are very helpful on this. If you have any further suggestions, please let me know. Otherwise, please close the issue.

Best,
Yue

**Comment by arkyl** [comment]
I forgot to ask about the significance threshold. Currently, we are using 0.05. Maybe you would have some advice on this, some set pval/Z or based on sample size (larger sample size requiring more significance?). Thanks!

**Comment by borangao** [comment]
> t we did observe a case where a gene has conflicting beta sign at a snp quite significant in both non-Hispanic White (NHW) and AA populations. The snp is a single snp CS and its configuration is shared across all 3 populations (pip.config=0.999). Its effect allele freq in 3 populations are NHW/AA/Hisp: 0.307/0.489/0.298; we noted the freq in AA is close to 0.5.

Dear Yue,

For fine-mapping signals that are not marginally significant, the cause could be either:

1. LD mismatch, where the signals are highly correlated with significant SNPs within the region (Technical).
2. Masking effects (Non-technical).
It’s worth checking for LD mismatches using the function provided by MESuSiE. We also annotated additional points that SuSiE might miss, such as non-significant GWAS signals that are in high LD with significant GWAS signals.

I hope this helps!

Best,
Boran

**Comment by borangao** [comment]
> I forgot to ask about the significance threshold. Currently, we are using 0.05. Maybe you would have some advice on this, some set pval/Z or based on sample size (larger sample size requiring more significance?). Thanks!

I agree with using 0.05. Probably adjust based on sample size.

**Comment by arkyl** [comment]
Hi,
Thanks much for your suggestions. 
As we used the same individual level data to perform the QTL and generate LD matrix, the LD mismatch check is not really required. However, to be safe, we still test and perform some LD mismatch check based on the MESuSiE tutorial. As expected, for the genes we had checked so far, there were very few or no LD mismtach snps found. For the example we mentioned in this thread of conflicting beta signs, no LD mismtach snps were found. I guess fundamentally we would like to finalize the results to have consistent beta sign regardless of the input. 
Thanks again for your help with this! Please close the thread.
Yue

**Comment by arkyl** [comment]
Hi,
Sorry but a related question, about ancestry-specific signals. Let's say there is a snp, quite significant in two populations, would MESuSiE call it ancestry-specific if it has different beta sign or there is some difference in two non-zero beta values. My understanding is that MESuSiE is identifying zero effect vs non-zero effect in populations, i.e mainly about significance rather than beta value difference. So MESuSiE would not call it ancestry-specific. I ask this because we are thinking about maybe doing some filtering on ancestry-specific signals, and we want to be on the safe side to call it specific and wouldn't want to be too complicated. Thank you very much for your advice!
Yue

**Comment by borangao** [comment]
Dear Yue,

For MESuSiE, it is likely to be classified as a shared signal as MESuSiE
assumes a heterogeneous effect size across the populations. You can further
test for effect size differences across populations using MESuSiE output
beta and variances.

Best,
Boran
Boran Gao
Ph.D. Candidate in Biostatistics
MPH Epidemiology
MS Biostatistics
University of Michigan School of Public health
7345462396

**Comment by arkyl** [comment]
Thanks much for the confirmation. I am unaware that MESuSiE output contains beta and var for the signal, or do you mean the input beta and var from summary stats?
Yue

**Comment by borangao** [comment]
I mean MESuSiE output of posterior variance of beta.

Best,
Boran
Boran Gao
Ph.D. Candidate in Biostatistics
MPH Epidemiology
MS Biostatistics
University of Michigan School of Public health
7345462396

**Comment by arkyl** [comment]
Thanks for clarification. What parameter is the posterior variance of beta in MESuSiE_res, or how to get it from MESuSiE_res? MESuSiE_res is the output from meSuSie_core().
Yue
